### ISSUE TITLE
企业微信通知

### ISSUE THREAD

**Issue by sexyfeifan** [htnanako/ndu#1]
企业微信通知开启后，会提示要开可信 ip...
`2024-02-05 03:14:28 - MainThread - ERROR: 企业微信推送失败：{'errcode': 60020, 'errmsg': 'not allow to access from your ip, hint: [1707074068426830714460135], from ip: 180.xxx.82.xx, more info at https://open.work.weixin.qq.com/devtool/query?e=60020'}`

**Comment by htnanako** [comment]
https://open.work.weixin.qq.com/devtool/query?e=60020
http://wx.nnk.im

**Comment by sexyfeifan** [comment]
mr 里知道怎么搞，ndu里就不会了
![CleanShot 2024-02-09 at 00 59 17@2x](https://github.com/htnanako/ndu/assets/36148825/9a4a87a7-53c8-4cb8-bcd9-cc4c14ad1ee1)

**Comment by sexyfeifan** [comment]
![CleanShot 2024-02-09 at 00 59 17@2x](https://github.com/htnanako/ndu/assets/36148825/b990ff26-4afc-4a45-b0e8-267537f81d83)
这里没懂不知道怎么填

**Comment by htnanako** [comment]
> ![CleanShot 2024-02-09 at 00 59 17@2x](https://github.com/htnanako/ndu/assets/36148825/b990ff26-4afc-4a45-b0e8-267537f81d83)
> 
> 这里没懂不知道怎么填

用mr把接收消息服务器URL给验证了就可以填可信ip了。

**Comment by sexyfeifan** [comment]
意思就是现用 mr 先做验证，然后等验证过了，再把 mr 还原成原来的是吧？
