### ISSUE TITLE
通知图标未使用自定义图片

### ISSUE THREAD

**Issue by huronzhu** [htnanako/ndu#3]
已配置*_notify_img的png图片url，但bark推送仍然使用的默认图标

**Comment by htnanako** [comment]
> 已配置*_notify_img的png图片url，但bark推送仍然使用的默认图标

![image](https://github.com/user-attachments/assets/88a1cb65-dcca-49aa-bb66-52f9272f5058)
你要不再仔细看看？

**Comment by huronzhu** [comment]
对，下一个问题就是*_notify_img这俩是哪里用的，bark通知图标和内容里没看到这两个图片的任何一个

**Comment by htnanako** [comment]
> 对，下一个问题就是*_notify_img这俩是哪里用的，bark通知图标和内容里没看到这两个图片的任何一个

你换个有图片的推送通道就看到了
